(() => {
"use strict";
const VERSION="3.0.0",API="https://api.spotify.com/v1",AUTH="https://accounts.spotify.com/authorize",TOKEN="https://accounts.spotify.com/api/token";
const SCOPES=["user-library-read","playlist-modify-private","playlist-read-private"],MAX_PLAYLIST_ITEMS=2500,PAGE_LIMIT=50,ADD_BATCH=100,NETWORK_RETRIES=8,FETCH_TIMEOUT_MS=30000;
const STORAGE_KEY="spotify_album_builder_v3_state",TOKEN_KEY="spotify_album_builder_v3_token",CLIENT_KEY="spotify_album_builder_client_id",DIAG_KEY="spotify_album_builder_v3_diagnostics";
const $=id=>document.getElementById(id),el={clientId:$("clientId"),saveClient:$("saveClient"),redirectUri:$("redirectUri"),copyRedirect:$("copyRedirect"),login:$("login"),logout:$("logout"),selfTest:$("selfTest"),start:$("start"),pause:$("pause"),exportDiagnostics:$("exportDiagnostics"),reset:$("reset"),connectionPill:$("connectionPill"),phase:$("phase"),cached:$("cached"),placed:$("placed"),playlist:$("playlist"),playlistSongs:$("playlistSongs"),totalSongs:$("totalSongs"),requests:$("requests"),retries:$("retries"),status:$("status"),percent:$("percent"),barFill:$("barFill"),log:$("log")};
let running=false,pauseRequested=false,requestChain=Promise.resolve();
function blank(){return{version:VERSION,phase:"idle",albumOffset:0,albums:[],trackCache:{},cacheIndex:0,buildIndex:0,playlistNumber:1,playlistId:null,playlistName:null,playlistCount:0,totalSongsAdded:0,requestCount:0,retryCount:0,pendingWrite:null,completedAlbumIds:[],retryUntil:0,startedAt:null,finishedAt:null}}
function getState(){try{return{...blank(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")}}catch{return blank()}}function save(s){localStorage.setItem(STORAGE_KEY,JSON.stringify(s));render(s)}
function getDiag(){try{return JSON.parse(localStorage.getItem(DIAG_KEY)||"[]")}catch{return[]}}function diag(x){const d=getDiag();d.push({time:new Date().toISOString(),...x});if(d.length>1500)d.splice(0,d.length-1500);localStorage.setItem(DIAG_KEY,JSON.stringify(d))}
function log(m,k="INFO"){const line=`[${new Date().toLocaleString()}] ${k}: ${m}`;el.log.textContent+=(el.log.textContent?"\n":"")+line;el.log.scrollTop=el.log.scrollHeight;diag({kind:k,message:m});console.log(line)}function status(m){el.status.textContent=m;log(m)}function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function redirectUri(){return location.origin+location.pathname}function clientId(){return localStorage.getItem(CLIENT_KEY)||""}function tokenData(){try{return JSON.parse(localStorage.getItem(TOKEN_KEY)||"null")}catch{return null}}function putToken(t){localStorage.setItem(TOKEN_KEY,JSON.stringify(t))}function clearToken(){localStorage.removeItem(TOKEN_KEY)}
function b64(bytes){let s="";bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}function randomString(n=64){const c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~",a=new Uint8Array(n);crypto.getRandomValues(a);return[...a].map(x=>c[x%c.length]).join("")}async function sha256(s){return new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)))}
function render(s=getState()){const total=s.albums.length,cached=Object.keys(s.trackCache||{}).length,pct=total?Math.floor((Math.min(total,cached)+Math.min(total,s.buildIndex))/(total*2)*100):0;el.phase.textContent=s.phase;el.cached.textContent=`${cached} / ${total}`;el.placed.textContent=`${s.buildIndex} / ${total}`;el.playlist.textContent=s.playlistName||"—";el.playlistSongs.textContent=`${s.playlistCount||0} / ${MAX_PLAYLIST_ITEMS}`;el.totalSongs.textContent=String(s.totalSongsAdded||0);el.requests.textContent=String(s.requestCount||0);el.retries.textContent=String(s.retryCount||0);el.percent.textContent=`${pct}%`;el.barFill.style.width=`${pct}%`}
function updateAuth(){const on=!!tokenData();el.connectionPill.textContent=on?"Connected":"Not connected";el.connectionPill.classList.toggle("connected",on);el.selfTest.disabled=!on||running;el.start.disabled=!on||running}
async function login(){if(!clientId())return alert("Save your Spotify Client ID first.");const verifier=randomString(96),challenge=b64(await sha256(verifier)),st=randomString(32);sessionStorage.setItem("v3_verifier",verifier);sessionStorage.setItem("v3_oauth_state",st);const q=new URLSearchParams({client_id:clientId(),response_type:"code",redirect_uri:redirectUri(),scope:SCOPES.join(" "),code_challenge_method:"S256",code_challenge:challenge,state:st,show_dialog:"true"});location.href=`${AUTH}?${q}`}
async function finishLogin(){const q=new URLSearchParams(location.search),code=q.get("code");if(!code)return;if(q.get("state")!==sessionStorage.getItem("v3_oauth_state"))throw new Error("OAuth state mismatch.");const body=new URLSearchParams({client_id:clientId(),grant_type:"authorization_code",code,redirect_uri:redirectUri(),code_verifier:sessionStorage.getItem("v3_verifier")});const res=await fetch(TOKEN,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(!res.ok)throw new Error(`Token exchange failed: ${res.status} ${await res.text()}`);const t=await res.json();t.expires_at=Date.now()+t.expires_in*1000-60000;putToken(t);history.replaceState({},document.title,redirectUri());status("Spotify login approved.")}
async function accessToken(){let t=tokenData();if(!t)throw new Error("Not logged in.");if(Date.now()<Number(t.expires_at||0))return t.access_token;const body=new URLSearchParams({client_id:clientId(),grant_type:"refresh_token",refresh_token:t.refresh_token});const res=await fetch(TOKEN,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(!res.ok){clearToken();throw new Error(`Token refresh failed: ${res.status} ${await res.text()}`)}const n=await res.json();t={...t,...n,refresh_token:n.refresh_token||t.refresh_token,expires_at:Date.now()+n.expires_in*1000-60000};putToken(t);return t.access_token}
function queued(task){const run=requestChain.then(task,task);requestChain=run.catch(()=>{});return run}async function fetchTimed(url,options){const c=new AbortController(),timer=setTimeout(()=>c.abort(),FETCH_TIMEOUT_MS);try{return await fetch(url,{...options,signal:c.signal})}finally{clearTimeout(timer)}}function backoff(a){return Math.min(60000,1500*(2**a))+Math.floor(Math.random()*800)}
async function api(path,options={}){return queued(async()=>{const method=(options.method||"GET").toUpperCase(),url=path.startsWith("http")?path:API+path;for(let attempt=0;attempt<=NETWORK_RETRIES;attempt++){let s=getState();s.requestCount++;save(s);const no=s.requestCount;log(`#${no} ${method} ${url}`);try{const headers=new Headers(options.headers||{});headers.set("Authorization",`Bearer ${await accessToken()}`);if(options.body&&!headers.has("Content-Type"))headers.set("Content-Type","application/json");const res=await fetchTimed(url,{...options,headers}),raw=await res.text();log(`#${no} ← ${res.status}`);diag({kind:"RESPONSE",requestNo:no,status:res.status,body:raw.slice(0,1000)});if(res.status===429){const sec=Math.max(1,Number(res.headers.get("Retry-After")||1));s=getState();s.retryCount++;save(s);log(`Spotify 429; retrying after ${sec}s.`,"WARN");await sleep(sec*1000);attempt--;continue}if([500,502,503,504].includes(res.status)&&attempt<NETWORK_RETRIES){s=getState();s.retryCount++;save(s);await sleep(backoff(attempt));continue}if(!res.ok)throw new Error(`${method} ${path} → Spotify ${res.status}: ${raw}`);return raw?JSON.parse(raw):null}catch(err){const network=err instanceof TypeError||err.name==="AbortError"||/Failed to fetch|NetworkError|Load failed/i.test(String(err.message||err));diag({kind:"FETCH_ERROR",requestNo:no,method,url,message:String(err.message||err),attempt});if(!network||attempt>=NETWORK_RETRIES)throw err;s=getState();s.retryCount++;save(s);const wait=backoff(attempt);log(`#${no} network failure; retry ${attempt+1}/${NETWORK_RETRIES} in ${Math.ceil(wait/1000)}s.`,"WARN");status(`Temporary network failure. Retrying automatically (${attempt+1}/${NETWORK_RETRIES})…`);await sleep(wait)}}throw new Error(`${method} ${path} exhausted retries.`)})}
async function selfTest(){try{status("Running self-test…");const me=await api("/me"),a=await api("/me/albums?limit=1");status(`Self-test passed for ${me.display_name||me.id}; ${a.total||0} saved album(s).`)}catch(e){status(`SELF-TEST ERROR: ${e.message||e}`)}}
async function collectAlbums(s){s.phase="collecting albums";save(s);let offset=s.albumOffset||0;while(true){if(pauseRequested)return false;const page=await api(`/me/albums?limit=${PAGE_LIMIT}&offset=${offset}`);for(const item of page.items||[]){const a=item.album;if(a?.id&&!s.albums.some(x=>x.id===a.id))s.albums.push({id:a.id,name:a.name,artist:(a.artists||[]).map(x=>x.name).join(", ")})}offset+=(page.items||[]).length;s.albumOffset=offset;save(s);status(`Found ${s.albums.length} saved album(s).`);if(!page.next||!(page.items||[]).length)break}s.albumOffset=0;s.phase="caching tracks";save(s);return true}
async function albumTracks(album){let out=[],offset=0;while(true){const p=await api(`/albums/${album.id}/tracks?limit=${PAGE_LIMIT}&offset=${offset}`);out.push(...(p.items||[]).map(x=>x.uri).filter(Boolean));offset+=(p.items||[]).length;if(!p.next||!(p.items||[]).length)break}return out}
async function cacheTracks(s){for(let i=s.cacheIndex||0;i<s.albums.length;i++){if(pauseRequested)return false;const a=s.albums[i];if(!s.trackCache[a.id]){status(`Caching ${a.artist} — ${a.name}`);s.trackCache[a.id]=await albumTracks(a)}s.cacheIndex=i+1;save(s)}s.phase="building playlists";save(s);return true}
async function findPlaylist(name){let offset=0;while(true){const p=await api(`/me/playlists?limit=50&offset=${offset}`),hit=(p.items||[]).find(x=>x.name===name);if(hit)return hit;offset+=(p.items||[]).length;if(!p.next||!(p.items||[]).length)return null}}
async function ensurePlaylist(s){if(s.playlistId)return;const name=`Album Playlist ${s.playlistNumber}`;let p=await findPlaylist(name);if(!p){try{p=await api("/me/playlists",{method:"POST",body:JSON.stringify({name,public:false,description:"Saved Spotify albums. Built by Album Playlist Builder V3."})})}catch(e){p=await findPlaylist(name);if(!p)throw e}}s.playlistId=p.id;s.playlistName=name;const info=await api(`/playlists/${p.id}?fields=id,name,items(total)`);s.playlistCount=Number(info?.items?.total||0);save(s);status(`Using ${name} (${s.playlistCount} item(s)).`)}
async function tailMatches(id,uris,start){const p=await api(`/playlists/${id}/items?limit=${uris.length}&offset=${start}`),actual=(p.items||[]).map(x=>x.item?.uri||x.track?.uri).filter(Boolean);return actual.length===uris.length&&actual.every((x,i)=>x===uris[i])}
async function addVerified(s,batch){const start=s.playlistCount;s.pendingWrite={playlistId:s.playlistId,start,uris:batch};save(s);try{await api(`/playlists/${s.playlistId}/items`,{method:"POST",body:JSON.stringify({uris:batch})})}catch(e){log("Write response uncertain; verifying exact playlist range.","WARN");if(!(await tailMatches(s.playlistId,batch,start)))throw e}if(!(await tailMatches(s.playlistId,batch,start)))throw new Error(`Verification failed at playlist offset ${start}.`);s.playlistCount+=batch.length;s.totalSongsAdded+=batch.length;s.pendingWrite=null;save(s)}
async function nextPlaylist(s){s.playlistNumber++;s.playlistId=null;s.playlistName=null;s.playlistCount=0;save(s);await ensurePlaylist(s)}
async function build(s){s.phase="building playlists";save(s);for(let i=s.buildIndex||0;i<s.albums.length;i++){if(pauseRequested)return false;s=getState();const a=s.albums[i],uris=s.trackCache[a.id]||[];status(`Placing ${a.artist} — ${a.name} (${uris.length} song(s))`);if(!uris.length){s.buildIndex=i+1;save(s);continue}await ensurePlaylist(s);if(s.playlistCount>0&&s.playlistCount+uris.length>MAX_PLAYLIST_ITEMS)await nextPlaylist(s);let cursor=0;while(cursor<uris.length){if(s.playlistCount>=MAX_PLAYLIST_ITEMS)await nextPlaylist(s);const capacity=MAX_PLAYLIST_ITEMS-s.playlistCount,batch=uris.slice(cursor,cursor+Math.min(ADD_BATCH,capacity));await addVerified(s,batch);cursor+=batch.length;status(`Verified ${batch.length} item(s) in ${s.playlistName}; ${s.playlistCount}/${MAX_PLAYLIST_ITEMS}.`)}s.buildIndex=i+1;save(s)}s.phase="complete";s.finishedAt=new Date().toISOString();save(s);status(`Complete. Added ${s.totalSongsAdded} songs across ${s.playlistNumber} playlist(s).`)}
async function run(){if(running)return;running=true;pauseRequested=false;el.pause.disabled=false;updateAuth();try{let s=getState();if(!s.startedAt){s.startedAt=new Date().toISOString();save(s)}if(!s.albums.length||s.phase==="collecting albums"){if(!(await collectAlbums(s)))return;s=getState()}if(Object.keys(s.trackCache).length<s.albums.length){if(!(await cacheTracks(s)))return;s=getState()}await build(s)}catch(e){log(e.stack||String(e),"ERROR");el.status.textContent=`ERROR: ${e.message||e}`}finally{running=false;el.pause.disabled=true;updateAuth();if(pauseRequested)status("Paused at a safe checkpoint.")}}
function exportDiagnostics(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),version:VERSION,userAgent:navigator.userAgent,state:getState(),diagnostics:getDiag()},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`spotify-album-builder-v3-diagnostics-${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href)}
el.saveClient.onclick=()=>{const v=el.clientId.value.trim();if(!v)return alert("Enter a Client ID.");localStorage.setItem(CLIENT_KEY,v);status("Client ID saved.")};el.copyRedirect.onclick=async()=>{await navigator.clipboard.writeText(redirectUri());status("Redirect URI copied.")};el.login.onclick=login;el.logout.onclick=()=>{clearToken();updateAuth();status("Spotify login forgotten.")};el.selfTest.onclick=selfTest;el.start.onclick=run;el.pause.onclick=()=>{pauseRequested=true;status("Pause requested; stopping after the current verified checkpoint.")};el.exportDiagnostics.onclick=exportDiagnostics;el.reset.onclick=()=>{if(confirm("Reset V3 progress? Existing Spotify playlists will not be deleted.")){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(DIAG_KEY);el.log.textContent="";save(blank());status("V3 progress reset.")}};
(async()=>{el.redirectUri.textContent=redirectUri();el.clientId.value=clientId();render();try{await finishLogin()}catch(e){el.status.textContent=`LOGIN ERROR: ${e.message||e}`;log(e.stack||String(e),"ERROR")}updateAuth()})();
})();